CREATE DATABASE `syanaikanri_db` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

CREATE TABLE `bk_m_user_detail_paid_holiday_start_day` (
  `company_code` char(6) CHARACTER SET utf8 NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT 'ユーザーID',
  `first_name` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT '姓',
  `last_name` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT '名',
  `first_name_kana` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓(カナ)',
  `last_name_kana` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '名(カナ)',
  `birthday` char(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '生年月日',
  `sex` char(1) CHARACTER SET utf8 DEFAULT '0' COMMENT '性別',
  `tel` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '電話番号',
  `zip` char(8) CHARACTER SET utf8 DEFAULT NULL COMMENT '郵便番号',
  `address_prefecture` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '住所（都道府県）',
  `address_municipality` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '住所（市区町村）',
  `address_town` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '住所（丁名・番地）',
  `address_detail` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '住所（部屋番号）',
  `join_date` char(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '入社年月',
  `paid_holiday_start_day` char(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '有休付与開始日',
  `probation_period_end_day` char(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '試用期間終了日',
  `leave_date` char(16) CHARACTER SET utf8 DEFAULT NULL COMMENT '退社年月',
  `del_flg` char(1) CHARACTER SET utf8 DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `k_m_user` (
  `company_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '会社コード',
  `user_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT 'ユーザーID',
  `first_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓',
  `last_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '名',
  `first_name_kana` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓（カナ）',
  `last_name_kana` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '名（カナ）',
  `birthday` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '生年月日',
  `sex` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '性別',
  `tel` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '電話番号',
  `zip` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '郵便番号',
  `address_prefecture` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '現住所（都道府県）',
  `address_municipality` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '現住所（市区町村）',
  `address_town` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '現住所（丁目・番地）',
  `address_detail` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '現住所（建物名・部屋番号）',
  `join_date` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '入社年月日',
  `leave_date` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '退職年月日',
  `del_flg` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '削除フラグ',
  `email` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT 'メアド',
  `employment_kbn` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '雇用業態区分',
  `department_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '部門コード',
  `position_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '役職コード'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `m_category` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `category_class_number` char(3) NOT NULL COMMENT '区分分類',
  `category_kbn` char(3) NOT NULL COMMENT '区分値',
  `category_kbn_name` varchar(255) NOT NULL COMMENT '区分値名称',
  `category_kbn_abbreviation` varchar(50) DEFAULT NULL COMMENT '区分値略称',
  `category_kbn_option1` varchar(255) DEFAULT NULL COMMENT '区分値オプション１',
  `category_kbn_option2` varchar(255) DEFAULT NULL COMMENT '区分値オプション２',
  `category_kbn_option3` varchar(255) DEFAULT NULL COMMENT '区分値オプション3',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`category_class_number`,`category_kbn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='区分マスタ';

CREATE TABLE `m_category_class` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `category_class_number` char(3) NOT NULL COMMENT '区分分類',
  `category_class_name` varchar(50) NOT NULL COMMENT '区分分類名',
  `category_system_flg` char(1) DEFAULT '0' COMMENT 'システム管理フラグ',
  `category_description` text COMMENT '説明',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`category_class_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='区分分類マスタ';

CREATE TABLE `m_company` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `company_name` varchar(100) NOT NULL COMMENT '会社名',
  `company_name_sh` varchar(50) NOT NULL COMMENT '会社略称',
  `company_tel` varchar(20) NOT NULL COMMENT '電話番号',
  `company_zip` varchar(8) DEFAULT NULL COMMENT '郵便番号',
  `address_prefecture` varchar(100) DEFAULT NULL COMMENT '住所（都道府県）',
  `address_municipality` varchar(100) DEFAULT NULL COMMENT '住所（市区町村）',
  `address_town` varchar(100) DEFAULT NULL COMMENT '住所（丁名・番地）',
  `address_detail` varchar(200) DEFAULT NULL COMMENT '住所（部屋番号）',
  `company_url` varchar(255) DEFAULT NULL COMMENT 'URL',
  `company_logo` varchar(100) DEFAULT NULL COMMENT '会社ロゴ',
  `company_image` varchar(100) DEFAULT NULL COMMENT '会社写真',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会社マスタ';

CREATE TABLE `m_department` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `department_code` char(8) NOT NULL COMMENT '部門コード',
  `start_date` char(8) NOT NULL COMMENT '適用開始日',
  `department_name` varchar(100) NOT NULL COMMENT '部門名',
  `department_name_sh` varchar(50) NOT NULL COMMENT '部門略称',
  `parent_dept_code` char(8) DEFAULT NULL COMMENT '親部門コード',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`department_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='部門マスタ';

CREATE TABLE `m_holiday` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `holiday_date` varchar(8) NOT NULL COMMENT '日付(yyyyMMdd)',
  `holiday_year` varchar(4) NOT NULL COMMENT '年(yyyy)',
  `holiday_month` varchar(2) DEFAULT NULL COMMENT '月(MM)',
  `holiday_day` varchar(2) DEFAULT NULL COMMENT '日(dd)',
  `holiday_name` varchar(50) DEFAULT NULL COMMENT '祝日名',
  `holiday_remark` varchar(255) DEFAULT '0' COMMENT '備考',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8 COMMENT='休日マスタ';

CREATE TABLE `m_menu` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `menu_number` char(2) NOT NULL COMMENT 'メニュー番号',
  `permission_kbn` char(3) NOT NULL COMMENT '権限区分',
  `available_flg` char(1) DEFAULT '0' COMMENT '利用可能フラグ',
  `option_value1` varchar(50) DEFAULT NULL COMMENT 'オプション１',
  `option_value2` varchar(50) DEFAULT NULL COMMENT 'オプション２',
  `option_value3` varchar(50) DEFAULT NULL COMMENT 'オプション３',
  `option_value4` varchar(50) DEFAULT NULL COMMENT 'オプション４',
  `option_value5` varchar(50) DEFAULT NULL COMMENT 'オプション５',
  `option_value6` varchar(50) DEFAULT NULL COMMENT 'オプション６',
  `option_value1_exp` varchar(255) DEFAULT NULL COMMENT 'オプション１説明',
  `option_value2_exp` varchar(255) DEFAULT NULL COMMENT 'オプション２説明',
  `option_value3_exp` varchar(255) DEFAULT NULL COMMENT 'オプション３説明',
  `option_value4_exp` varchar(255) DEFAULT NULL COMMENT 'オプション４説明',
  `option_value5_exp` varchar(255) DEFAULT NULL COMMENT 'オプション５説明',
  `option_value6_exp` varchar(255) DEFAULT NULL COMMENT 'オプション６説明',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`menu_number`,`permission_kbn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='メニューマスタ';

CREATE TABLE `m_menu_style` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `menu_number` char(2) NOT NULL COMMENT 'メニュー番号',
  `menu_button_name` varchar(20) DEFAULT NULL COMMENT 'メニュー名',
  `button_color` varchar(8) DEFAULT NULL COMMENT 'ボタン色',
  `font_color` varchar(8) DEFAULT NULL COMMENT 'フォント色',
  `font_size` tinyint(3) unsigned DEFAULT NULL COMMENT 'フォントサイズ',
  `menu_disp_url` varchar(255) DEFAULT NULL COMMENT '画面URL',
  `menu_icon` varchar(255) DEFAULT NULL COMMENT 'アイコン',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`menu_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='メニュースタイルマスタ';

CREATE TABLE `m_permission` (
  `company_code` char(50) CHARACTER SET utf8 NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT 'ユーザーID',
  `permission_kbn` char(3) CHARACTER SET utf8 NOT NULL COMMENT '権限区分',
  PRIMARY KEY (`company_code`,`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='権限マスタ';

CREATE TABLE `m_user` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `user_name` varchar(100) NOT NULL COMMENT '名前',
  `start_date` char(16) NOT NULL COMMENT '適用開始日',
  `pass_word` varchar(100) NOT NULL COMMENT 'パスワード',
  `email` varchar(255) NOT NULL COMMENT 'メールアドレス',
  `account_kbn` char(3) NOT NULL COMMENT '利用者区分',
  `permission_kbn` char(3) NOT NULL COMMENT '権限区分',
  `employment_kbn` char(3) DEFAULT NULL,
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  `image_url` text COMMENT 'イメージURI',
  PRIMARY KEY (`company_code`,`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='利用者マスタ（基本情報）';

CREATE TABLE `m_user_detail` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `first_name` varchar(20) NOT NULL COMMENT '姓',
  `last_name` varchar(20) NOT NULL COMMENT '名',
  `first_name_kana` varchar(50) DEFAULT NULL COMMENT '姓(カナ)',
  `last_name_kana` varchar(50) DEFAULT NULL COMMENT '名(カナ)',
  `birthday` char(16) DEFAULT NULL COMMENT '生年月日',
  `sex` char(1) DEFAULT '0' COMMENT '性別',
  `tel` varchar(20) DEFAULT NULL COMMENT '電話番号',
  `zip` char(8) DEFAULT NULL COMMENT '郵便番号',
  `address_prefecture` varchar(100) DEFAULT NULL COMMENT '住所（都道府県）',
  `address_municipality` varchar(100) DEFAULT NULL COMMENT '住所（市区町村）',
  `address_town` varchar(100) DEFAULT NULL COMMENT '住所（丁名・番地）',
  `address_detail` varchar(200) DEFAULT NULL COMMENT '住所（部屋番号）',
  `join_date` char(16) DEFAULT NULL COMMENT '入社年月',
  `paid_holiday_start_day` char(16) DEFAULT NULL COMMENT '有休付与開始日',
  `probation_period_end_day` char(16) DEFAULT NULL COMMENT '試用期間終了日',
  `leave_date` char(16) DEFAULT NULL COMMENT '退社年月',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='利用者マスタ（詳細情報）';

CREATE TABLE `t_attendance` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `work_date` char(8) NOT NULL COMMENT '日付(yyyyMMdd)',
  `work_date_ym` char(6) NOT NULL COMMENT '年月(yyyyMM)',
  `work_date_week` char(1) NOT NULL COMMENT '曜日',
  `work_kbn` char(3) NOT NULL COMMENT '勤怠区分',
  `work_start1` datetime DEFAULT NULL COMMENT '出勤時間_1',
  `work_end1` datetime DEFAULT NULL COMMENT '退勤時間_1',
  `work_start2` datetime DEFAULT NULL COMMENT '出勤時間_2',
  `work_end2` datetime DEFAULT NULL COMMENT '退勤時間_2',
  `work_start3` datetime DEFAULT NULL COMMENT '出勤時間_3',
  `work_end3` datetime DEFAULT NULL COMMENT '退勤時間_3',
  `work_time` time DEFAULT NULL COMMENT '労働時間',
  `work_break_time1` time DEFAULT NULL COMMENT '休憩時間_1',
  `work_break_time2` time DEFAULT NULL COMMENT '休憩時間_2',
  `work_break_time3` time DEFAULT NULL COMMENT '休憩時間_3',
  `work_over_time` time DEFAULT NULL COMMENT '普通残業',
  `work_midnight_time` time DEFAULT NULL COMMENT '深夜残業',
  `work_holi_time` time DEFAULT NULL COMMENT '労働時間（休日）',
  `work_midnight_holi_time` time DEFAULT NULL COMMENT '深夜残業（休日）',
  `work_sum_holi_time` time DEFAULT NULL COMMENT '休憩合計時間',
  `work_sum_time` time DEFAULT NULL COMMENT '合計時間',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `send_report_flg` char(1) DEFAULT '0' COMMENT '日報入力フラグ',
  `work_tc_start1` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_1',
  `work_tc_end1` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_1',
  `work_tc_start2` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_2',
  `work_tc_end2` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_2',
  `work_tc_start3` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_3',
  `work_tc_end3` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_3',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`work_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='勤怠テーブル';

CREATE TABLE `t_attendance_history` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `history_no` varchar(2) NOT NULL COMMENT '履歴番号',
  `work_date` char(8) NOT NULL COMMENT '日付(yyyyMMdd)',
  `work_date_ym` char(6) NOT NULL COMMENT '年月(yyyyMM)',
  `work_date_week` char(1) NOT NULL COMMENT '曜日',
  `work_kbn` char(3) NOT NULL COMMENT '勤怠区分',
  `work_start1` datetime DEFAULT NULL COMMENT '出勤時間_1',
  `work_end1` datetime DEFAULT NULL COMMENT '退勤時間_1',
  `work_start2` datetime DEFAULT NULL COMMENT '出勤時間_2',
  `work_end2` datetime DEFAULT NULL COMMENT '退勤時間_2',
  `work_start3` datetime DEFAULT NULL COMMENT '出勤時間_3',
  `work_end3` datetime DEFAULT NULL COMMENT '退勤時間_3',
  `work_time` time DEFAULT NULL COMMENT '労働時間',
  `work_break_time1` time DEFAULT NULL COMMENT '休憩時間_1',
  `work_break_time2` time DEFAULT NULL COMMENT '休憩時間_2',
  `work_break_time3` time DEFAULT NULL COMMENT '休憩時間_3',
  `work_over_time` time DEFAULT NULL COMMENT '普通残業',
  `work_midnight_time` time DEFAULT NULL COMMENT '深夜残業',
  `work_holi_time` time DEFAULT NULL COMMENT '労働時間（休日）',
  `work_midnight_holi_time` time DEFAULT NULL COMMENT '深夜残業（休日）',
  `work_sum_holi_time` time DEFAULT NULL COMMENT '休憩合計時間',
  `work_sum_time` time DEFAULT NULL COMMENT '合計時間',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `send_report_flg` char(1) DEFAULT '0' COMMENT '日報入力フラグ',
  `work_tc_start1` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_1',
  `work_tc_end1` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_1',
  `work_tc_start2` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_2',
  `work_tc_end2` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_2',
  `work_tc_start3` datetime DEFAULT NULL COMMENT 'ＴＣ出勤時間_3',
  `work_tc_end3` datetime DEFAULT NULL COMMENT 'ＴＣ退勤時間_3',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`history_no`,`work_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='勤怠履歴テーブル';

CREATE TABLE `t_attendance_stting` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `application_date` char(8) NOT NULL COMMENT '適用開始日',
  `work_prescribed_time` time NOT NULL COMMENT '所定労働時間',
  `work_every_time` tinyint(4) NOT NULL COMMENT '時間計算単位',
  `work_start_time` time NOT NULL COMMENT '始業時間',
  `work_end_time` time NOT NULL COMMENT '終業時間',
  `work_break_start1` time NOT NULL COMMENT '休憩開始時間_1',
  `work_break_end1` time DEFAULT NULL COMMENT '休憩終了時間_1',
  `work_break_start2` time DEFAULT NULL COMMENT '休憩開始時間_2',
  `work_break_end2` time DEFAULT NULL COMMENT '休憩終了時間_2',
  `work_break_start3` time DEFAULT NULL COMMENT '休憩開始時間_3',
  `work_break_end3` time DEFAULT NULL COMMENT '休憩終了時間_3',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`application_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='勤怠設定テーブル';

CREATE TABLE `t_belong_dept` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `department_code` char(8) NOT NULL COMMENT '部門コード',
  `position_code` varchar(6) DEFAULT NULL COMMENT '役職コード',
  `priority_level` char(1) NOT NULL COMMENT '優先順',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`department_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='所属部門テーブル';

CREATE TABLE `t_day_check_history` (
  `company_code` char(6) CHARACTER SET utf8 NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT 'ユーザID',
  `check_day` char(8) CHARACTER SET utf8 NOT NULL COMMENT 'チェック日',
  `branch_number` int(5) NOT NULL COMMENT '枝番',
  `err_cd` char(2) CHARACTER SET utf8 NOT NULL COMMENT 'エラーコード',
  `err_message` varchar(200) CHARACTER SET utf8 NOT NULL COMMENT 'エラーメッセージ',
  `registration_user` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  `update_user` varchar(30) CHARACTER SET utf8 DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`check_day`,`branch_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='日別チェック処理履歴テーブル';

CREATE TABLE `t_exchanged_workday` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `work_type_kbn` char(3) NOT NULL COMMENT '申請種類区分',
  `scheduled_work_day` char(8) NOT NULL COMMENT '休日出勤予定日',
  `work_time_kbn` char(3) NOT NULL COMMENT '休日出勤時刻区分',
  `dayoff_exchanged` char(8) NOT NULL COMMENT '振休取得予定日',
  `dayoff_time_kbn` char(3) NOT NULL COMMENT '振休時刻区分',
  `dayoff_reason_kbn` char(3) NOT NULL COMMENT '休日出勤理由区分',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`,`request_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='振替出勤申請内容テーブル';

CREATE TABLE `t_group` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `group_code` char(6) NOT NULL COMMENT 'グループコード',
  `group_name` varchar(50) NOT NULL COMMENT 'グループ名',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`group_code`,`group_name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='グループテーブル';

CREATE TABLE `t_group_member` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `group_code` char(6) NOT NULL COMMENT 'グループコード',
  `group_user_id` varchar(20) NOT NULL COMMENT 'グループメンバー',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`group_code`,`group_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='グループメンバーテーブル';

CREATE TABLE `t_month_close_history` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザID',
  `close_month` char(6) NOT NULL COMMENT '対象年月',
  `process_day` char(8) DEFAULT NULL COMMENT '締処理日',
  `process_id` varchar(20) NOT NULL COMMENT '処理ID',
  `process_result` char(1) DEFAULT NULL COMMENT '結果区分',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`close_month`,`process_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='月締処理履歴テーブル';

CREATE TABLE `t_month_close_process` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `process_id` varchar(20) NOT NULL COMMENT '処理ID',
  `process_day` char(8) NOT NULL COMMENT '処理日',
  `process_kbn` char(2) DEFAULT NULL COMMENT '処理区分',
  `close_month` char(6) DEFAULT NULL COMMENT '対象年月',
  `tgt_user_id` varchar(20) DEFAULT NULL COMMENT '処理対象',
  `process_status` char(1) DEFAULT NULL COMMENT 'ステータス',
  `process_result` char(1) DEFAULT NULL COMMENT '処理結果区分',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`process_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='月締処理管理テーブル';

CREATE TABLE `t_notice` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `notice_number` char(10) NOT NULL COMMENT 'お知らせ番号',
  `notice_category` char(3) NOT NULL DEFAULT '001' COMMENT 'カテゴリー',
  `notice_publication_start_date` char(10) NOT NULL COMMENT '掲載日時',
  `notice_publication_end_date` char(10) NOT NULL COMMENT '終了日時',
  `notice_title` varchar(50) NOT NULL COMMENT 'タイトル',
  `notice_contents` text NOT NULL COMMENT '内容',
  `notice_new_period` tinyint(3) unsigned DEFAULT NULL COMMENT '新規期間',
  `notice_attachment1` varchar(255) DEFAULT NULL COMMENT '添付１',
  `notice_attachment2` varchar(255) DEFAULT NULL COMMENT '添付２',
  `notice_attachment3` varchar(255) DEFAULT NULL COMMENT '添付３',
  `registration_user` varchar(30) DEFAULT NULL,
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL,
  `update_datetime` datetime DEFAULT NULL,
  PRIMARY KEY (`company_code`,`notice_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='お知らせテーブル';

CREATE TABLE `t_overtime` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `work_type_kbn` char(3) NOT NULL COMMENT '申請種類区分',
  `scheduled_overtime_day` char(8) NOT NULL COMMENT '深夜残業予定日',
  `start_time` datetime NOT NULL COMMENT '開始予定時間',
  `end_time` datetime NOT NULL COMMENT '終了予定時間',
  `estimated_work_hours` time NOT NULL COMMENT '予定時間数',
  `overtime_reason_kbn` char(3) NOT NULL COMMENT '残業理由区分',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`,`request_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='深夜残業申請内容テーブル';

CREATE TABLE `t_paid_holiday` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `date_ym` char(6) NOT NULL COMMENT '年月',
  `assignment_year` char(4) NOT NULL COMMENT '付与年度',
  `assignment_day` char(8) DEFAULT NULL COMMENT '付与日',
  `paid_holiday_remaining` float(3,1) DEFAULT '0.0' COMMENT '残数',
  `expired_ymd` char(8) DEFAULT NULL COMMENT '失効年月日',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`date_ym`,`assignment_year`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='有休残テーブル';

CREATE TABLE `t_paid_holiday_history` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `target_date` char(8) NOT NULL COMMENT '対象日',
  `paid_holiday_ope_kbn` char(3) NOT NULL COMMENT '有休操作区分',
  `paid_holiday_days` float(3,1) NOT NULL COMMENT '日数',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`target_date`,`paid_holiday_ope_kbn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='有休履歴テーブル';

CREATE TABLE `t_request` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `request_status_kbn` char(3) NOT NULL COMMENT '状態区分',
  `request_date` char(8) NOT NULL COMMENT '申請日',
  `request_type_kbn` char(3) NOT NULL COMMENT '申請種類区分',
  `request_overview` varchar(255) DEFAULT NULL COMMENT '申請概要',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='申請テーブル';

CREATE TABLE `t_request_allowance` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `apply_ym` char(6) NOT NULL COMMENT '年月',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_type_kbn` char(3) NOT NULL COMMENT '申請種類区分',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `allowance` int(8) DEFAULT NULL COMMENT '手当金額',
  `quantity` int(3) DEFAULT NULL COMMENT '手当口数',
  `total` int(8) DEFAULT NULL COMMENT '手当合計',
  `project_id` varchar(8) DEFAULT NULL COMMENT '作番ID',
  `project_name` varchar(255) DEFAULT NULL COMMENT '作番名',
  `qualification_id` char(3) DEFAULT NULL COMMENT '資格ID',
  `qualification_exam_date` char(8) DEFAULT NULL COMMENT '資格受検日',
  `image` varchar(255) DEFAULT NULL COMMENT '添付画像',
  `remark_1` varchar(255) DEFAULT NULL COMMENT '備考１',
  `remark_2` varchar(255) DEFAULT NULL COMMENT '備考２',
  `remark_3` varchar(255) DEFAULT NULL COMMENT '備考３',
  `remark_4` varchar(255) DEFAULT NULL COMMENT '備考４',
  `remark_5` varchar(255) DEFAULT NULL COMMENT '備考５',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`apply_ym`,`request_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='手当申請テーブル';

CREATE TABLE `t_request_attendance` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `work_date_ym` char(6) NOT NULL COMMENT '年月(yyyyMM)',
  `request_number` varchar(50) DEFAULT NULL COMMENT '申請番号',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`work_date_ym`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='勤怠申請テーブル';

CREATE TABLE `t_request_holiday` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_sub_number` tinyint(4) NOT NULL COMMENT '枝番',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `holiday_type_kbn` char(3) NOT NULL COMMENT '休暇種類区分',
  `holiday_plan_day` char(8) NOT NULL COMMENT '休暇予定日',
  `holiday_time_kbn` char(3) NOT NULL COMMENT '休暇時刻区分',
  `holiday_days` float(3,1) DEFAULT '0.0' COMMENT '休暇日数',
  `holiday_reason_kbn` char(3) DEFAULT NULL COMMENT '休暇理由区分',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `work_dayoff_request_number` varchar(50) DEFAULT NULL COMMENT '休日出勤申請番号',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`,`request_sub_number`,`request_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='休暇申請内容テーブル';

CREATE TABLE `t_resume` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `resume_ver_kbn` varchar(20) NOT NULL COMMENT '経歴書バージョン',
  `nearest_station` varchar(20) NOT NULL COMMENT '最寄り駅',
  `graduation_ym` char(6) NOT NULL COMMENT '卒業年月',
  `degree` varchar(20) DEFAULT NULL COMMENT '学位',
  `school_name` varchar(50) DEFAULT NULL COMMENT '学校名',
  `major` varchar(20) DEFAULT NULL COMMENT '専攻学科',
  `certification1` varchar(256) DEFAULT NULL COMMENT '資格１',
  `certification2` varchar(256) DEFAULT NULL COMMENT '資格２',
  `certification3` varchar(256) DEFAULT NULL COMMENT '資格３',
  `certification4` varchar(256) DEFAULT NULL COMMENT '資格４',
  `certification5` varchar(256) DEFAULT NULL COMMENT '資格５',
  `certification6` varchar(256) DEFAULT NULL COMMENT '資格６',
  `experience_years` float(3,1) DEFAULT '0.0' COMMENT '経験年数',
  `responsible` varchar(10) DEFAULT NULL COMMENT '役割',
  `lg_jp_business_con` char(3) NOT NULL COMMENT '語学能力_業務会話（日本語）',
  `lg_jp_daily_con` char(3) NOT NULL COMMENT '語学能力_日常会話（日本語）',
  `lg_jp_reading` char(3) NOT NULL COMMENT '語学能力_読解能力（日本語）',
  `lg_jp_listening` char(3) NOT NULL COMMENT '語学能力_聴解能力（日本語）',
  `lg_jp_writting` char(3) NOT NULL COMMENT '語学能力_書く能力（日本語）',
  `lg_en_business_con` char(3) NOT NULL COMMENT '語学能力_業務会話（英語）',
  `lg_en_daily_con` char(3) NOT NULL COMMENT '語学能力_日常会話（英語）',
  `lg_en_reading` char(3) NOT NULL COMMENT '語学能力_読解能力（英語）',
  `lg_en_listening` char(3) NOT NULL COMMENT '語学能力_聴解能力（英語）',
  `lg_en_writting` char(3) NOT NULL COMMENT '語学能力_書く能力（英語）',
  `tc_os_windows` char(3) NOT NULL COMMENT '技術能力_Windows',
  `tc_os_unix` char(3) NOT NULL COMMENT '技術能力_UNIX',
  `tc_os_solaris` char(3) NOT NULL COMMENT '技術能力_Solaris',
  `tc_os_hpux` char(3) NOT NULL COMMENT '技術能力_HP-UX',
  `tc_os_aix` char(3) NOT NULL COMMENT '技術能力_AIX',
  `tc_os_linux` char(3) NOT NULL COMMENT '技術能力_Linux',
  `tc_os_dos` char(3) NOT NULL COMMENT '技術能力_DOS',
  `tc_os_mac` char(3) NOT NULL COMMENT '技術能力_Mac',
  `tc_pg_cobol` char(3) NOT NULL COMMENT '技術能力_COBOL',
  `tc_pg_java` char(3) NOT NULL COMMENT '技術能力_JAVA',
  `tc_pg_jsp` char(3) NOT NULL COMMENT '技術能力_JSP',
  `tc_pg_c` char(3) NOT NULL COMMENT '技術能力_C/C++',
  `tc_pg_vb` char(3) NOT NULL COMMENT '技術能力_VB',
  `tc_pg_vc` char(3) NOT NULL COMMENT '技術能力_VC/VC++',
  `tc_pg_sql` char(3) NOT NULL COMMENT '技術能力_SQL/PLSQL',
  `tc_pg_net` char(3) NOT NULL COMMENT '技術能力_.NET',
  `tc_pg_perl` char(3) NOT NULL COMMENT '技術能力_Perl',
  `tc_pg_xml` char(3) NOT NULL COMMENT '技術能力_XML',
  `tc_db_oracle` char(3) NOT NULL COMMENT '技術能力_ORACLE',
  `tc_db_hirdb` char(3) NOT NULL COMMENT '技術能力_HiRDB',
  `tc_db_sqlserver` char(3) NOT NULL COMMENT '技術能力_SQLServer',
  `tc_db_db2` char(3) NOT NULL COMMENT '技術能力_DB2',
  `tc_db_mysql` char(3) NOT NULL COMMENT '技術能力_MySQL',
  `tc_db_postgresql` char(3) NOT NULL COMMENT '技術能力_PostgreSQL',
  `tc_db_access` char(3) NOT NULL COMMENT '技術能力_ACCESS',
  `tc_etc_weblogic` char(3) NOT NULL COMMENT '技術能力_WebLogic',
  `tc_etc_j2ee` char(3) NOT NULL COMMENT '技術能力_J2EE',
  `tc_etc_websphere` char(3) NOT NULL COMMENT '技術能力_WebSphere',
  `tc_etc_tomcat` char(3) NOT NULL COMMENT '技術能力_Tomcat',
  `tc_etc_jp1` char(3) NOT NULL COMMENT '技術能力_JP1',
  `tc_etc_cosminexus` char(3) NOT NULL COMMENT '技術能力_Cosminexus',
  `tc_etc_xamarin` char(3) NOT NULL COMMENT '技術能力_Xamarin',
  `remarks` varchar(500) DEFAULT NULL COMMENT '備考',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`resume_ver_kbn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='経歴書基本情報';

CREATE TABLE `t_resume_detail` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `resume_ver_kbn` varchar(20) NOT NULL COMMENT '経歴書バージョン',
  `resume_seq_no` char(2) NOT NULL COMMENT '経歴シーケンス番号',
  `develop_period_from` char(8) NOT NULL COMMENT '開発期間From',
  `develop_period_to` char(8) DEFAULT NULL COMMENT '開発期間To',
  `develop_summary_sys` varchar(100) NOT NULL COMMENT '開発概要（システム名）',
  `develop_summary_sry` varchar(500) NOT NULL COMMENT '開発概要（概要）',
  `develop_summary_cts` varchar(500) NOT NULL COMMENT '開発概要（開発内容）',
  `develop_summary_mbs` varchar(50) NOT NULL COMMENT '開発概要（人数）',
  `develop_language_1` varchar(50) DEFAULT NULL COMMENT '使用言語_1',
  `develop_language_2` varchar(50) DEFAULT NULL COMMENT '使用言語_2',
  `develop_language_3` varchar(50) DEFAULT NULL COMMENT '使用言語_3',
  `develop_db_1` varchar(50) DEFAULT NULL COMMENT '使用DB_1',
  `develop_db_2` varchar(50) DEFAULT NULL COMMENT '使用DB_2',
  `develop_db_3` varchar(50) DEFAULT NULL COMMENT '使用DB_3',
  `develop_os_1` varchar(50) DEFAULT NULL COMMENT '使用OS_1',
  `develop_os_2` varchar(50) DEFAULT NULL COMMENT '使用OS_2',
  `develop_os_3` varchar(50) DEFAULT NULL COMMENT '使用OS_3',
  `responsible` varchar(10) DEFAULT NULL COMMENT '役割',
  `requirements_flg` char(1) DEFAULT '0' COMMENT '要件フラグ',
  `basic_flg` char(1) DEFAULT '0' COMMENT '基本設計フラグ',
  `specific_flg` char(1) DEFAULT '0' COMMENT '詳細設計フラグ',
  `coding_flg` char(1) DEFAULT '0' COMMENT 'コーディングフラグ',
  `unit_test_flg` char(1) DEFAULT '0' COMMENT '単体テストフラグ',
  `interface_test_flg` char(1) DEFAULT '0' COMMENT '結合テストフラグ',
  `system_test_flg` char(1) DEFAULT '0' COMMENT '運用テストフラグ',
  `del_flg` char(1) DEFAULT '0' COMMENT '削除フラグ',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時',
  `upd_account` varchar(30) DEFAULT NULL COMMENT '更新者',
  `upd_time` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`resume_ver_kbn`,`resume_seq_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='経歴書詳細情報';

CREATE TABLE `t_sub_holiday` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `holiday_work_day` char(8) NOT NULL COMMENT '休日出勤日',
  `sub_holiday_days` float(3,1) NOT NULL COMMENT '日数',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`holiday_work_day`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='代休残テーブル';

CREATE TABLE `t_sub_holiday_history` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `user_id` varchar(20) NOT NULL COMMENT 'ユーザーID',
  `target_date` char(8) NOT NULL COMMENT '対象日',
  `sub_holiday_ope_kbn` char(3) NOT NULL COMMENT '代休操作区分',
  `sub_holiday_days` float(3,1) NOT NULL COMMENT '日数',
  `work_day_request_number` varchar(50) NOT NULL COMMENT '休日出勤申請番号',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`user_id`,`target_date`,`sub_holiday_ope_kbn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='代休履歴テーブル';

CREATE TABLE `t_transportation_expenses` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `apply_ym` char(6) NOT NULL COMMENT '年月',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_sub_number` tinyint(4) NOT NULL COMMENT '枝番',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `start_date` char(8) DEFAULT NULL COMMENT '開始日',
  `end_date` char(8) DEFAULT NULL COMMENT '終了日',
  `month_kbn` char(2) DEFAULT NULL COMMENT '月区分',
  `days` int(3) DEFAULT NULL COMMENT '日数',
  `apply_kbn` char(3) DEFAULT NULL COMMENT '申請区分',
  `travel_kbn` char(3) DEFAULT NULL COMMENT '旅費区分',
  `departure` varchar(50) DEFAULT NULL COMMENT '出発',
  `arrival` varchar(50) DEFAULT NULL COMMENT '到着',
  `way_kbn` char(3) DEFAULT NULL COMMENT '往復区分',
  `destination` varchar(50) DEFAULT NULL COMMENT '目的地',
  `amount` int(8) DEFAULT NULL COMMENT '金額',
  `recipient_kbn` char(3) DEFAULT NULL COMMENT '請求区分',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `image` varchar(255) DEFAULT NULL COMMENT '画像',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`apply_ym`,`request_number`,`request_sub_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交通費申請内容テーブル';

CREATE TABLE `t_wf` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `req_app_order` tinyint(3) unsigned NOT NULL COMMENT '申請・承認順',
  `req_app_user_id` varchar(20) NOT NULL COMMENT '申請・承認者',
  `req_app_kbn` char(3) NOT NULL COMMENT '申請承認区分',
  `wf_status_kbn` char(3) NOT NULL COMMENT 'ワークフロー状態区分',
  `req_app_comment` varchar(255) DEFAULT NULL COMMENT 'コメント欄',
  `req_app_datetime` datetime DEFAULT NULL COMMENT '申請・承認日時',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`,`req_app_order`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ワークフローテーブル';

CREATE TABLE `t_work_dayoff` (
  `company_code` char(6) NOT NULL COMMENT '会社コード',
  `request_number` varchar(50) NOT NULL COMMENT '申請番号',
  `request_user_id` varchar(20) NOT NULL COMMENT '申請者',
  `work_type_kbn` char(3) NOT NULL COMMENT '申請種類区分',
  `scheduled_work_day` char(8) NOT NULL COMMENT '休日出勤予定日',
  `work_time_kbn` char(3) NOT NULL COMMENT '休日出勤時刻区分',
  `work_reason_kbn` char(3) NOT NULL COMMENT '休日出勤理由区分',
  `remark` varchar(255) DEFAULT NULL COMMENT '備考',
  `registration_user` varchar(30) DEFAULT NULL COMMENT '登録者',
  `registration_datetime` datetime DEFAULT NULL COMMENT '登録日時',
  `update_user` varchar(30) DEFAULT NULL COMMENT '更新者',
  `update_datetime` datetime DEFAULT NULL COMMENT '更新日時',
  PRIMARY KEY (`company_code`,`request_number`,`request_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='休日出勤申請内容テーブル';

CREATE TABLE `w_department_csv` (
  `item1` varchar(255) DEFAULT NULL COMMENT 'code',
  `item2` varchar(255) DEFAULT NULL COMMENT 'level1',
  `item3` varchar(255) DEFAULT NULL COMMENT 'level2',
  `item4` varchar(255) DEFAULT NULL COMMENT 'level3',
  `item5` varchar(255) DEFAULT NULL COMMENT 'level4',
  `item6` varchar(255) DEFAULT NULL COMMENT 'level5',
  `item7` varchar(255) DEFAULT NULL COMMENT 'level6',
  `item8` varchar(255) DEFAULT NULL COMMENT 'level7',
  `item9` varchar(255) DEFAULT NULL COMMENT 'level8',
  `item10` varchar(255) DEFAULT NULL COMMENT 'level9',
  `item11` varchar(255) DEFAULT NULL COMMENT 'level10',
  `item12` varchar(255) DEFAULT NULL COMMENT '予備１',
  `item13` varchar(255) DEFAULT NULL COMMENT '予備２',
  `item14` varchar(255) DEFAULT NULL COMMENT '予備３',
  `item15` varchar(255) DEFAULT NULL COMMENT '予備４',
  `item16` varchar(255) DEFAULT NULL COMMENT '予備５',
  `item17` varchar(255) DEFAULT NULL COMMENT '予備６',
  `item18` varchar(255) DEFAULT NULL COMMENT '予備７',
  `item19` varchar(255) DEFAULT NULL COMMENT '予備８',
  `item20` varchar(255) DEFAULT NULL COMMENT '予備９',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='部署データ取込ワーク';

CREATE TABLE `w_user_csv` (
  `item1` varchar(255) DEFAULT NULL COMMENT '社員番号',
  `item2` varchar(255) DEFAULT NULL COMMENT '姓',
  `item3` varchar(255) DEFAULT NULL COMMENT '名',
  `item4` varchar(255) DEFAULT NULL COMMENT '部署１部署名',
  `item5` varchar(255) DEFAULT NULL COMMENT '部署２部署名',
  `item6` varchar(255) DEFAULT NULL COMMENT '役職',
  `item7` varchar(255) DEFAULT NULL COMMENT '雇用形態',
  `item8` varchar(255) DEFAULT NULL COMMENT '雇い入れ年月日（入社年月日）',
  `item9` varchar(255) DEFAULT NULL COMMENT '生年月日',
  `item10` varchar(255) DEFAULT NULL COMMENT '予備１',
  `item11` varchar(255) DEFAULT NULL COMMENT '予備２',
  `item12` varchar(255) DEFAULT NULL COMMENT '予備３',
  `item13` varchar(255) DEFAULT NULL COMMENT '予備４',
  `item14` varchar(255) DEFAULT NULL COMMENT '予備５',
  `item15` varchar(255) DEFAULT NULL COMMENT '予備６',
  `item16` varchar(255) DEFAULT NULL COMMENT '予備７',
  `item17` varchar(255) DEFAULT NULL COMMENT '予備８',
  `item18` varchar(255) DEFAULT NULL COMMENT '予備９',
  `item19` varchar(255) DEFAULT NULL COMMENT '予備１０',
  `item20` varchar(255) DEFAULT NULL COMMENT '予備１２',
  `reg_account` varchar(30) DEFAULT NULL COMMENT '登録者',
  `reg_time` datetime DEFAULT NULL COMMENT '登録日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='利用者データ取込ワーク';